//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Scripts/Input/GameControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameControls"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""3133d8ae-b162-423a-a24e-5823fbc5a776"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""f876f445-5ff8-4221-ab84-320df58e70f5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Cast Skill 1"",
                    ""type"": ""Button"",
                    ""id"": ""4d09e53c-e24b-4438-a936-384804992314"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cast Skill 2"",
                    ""type"": ""Button"",
                    ""id"": ""76387dfb-f47c-4855-a709-ce5be13105f6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cast Skill 3"",
                    ""type"": ""Button"",
                    ""id"": ""61199924-45fa-48c2-85c9-b0741297d4d7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cast Skill 4"",
                    ""type"": ""Button"",
                    ""id"": ""f67749f4-6920-44f0-b481-a4f8439dd7a7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""2146eb4f-2383-4621-aad4-4d5ec894f92b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7fa8784b-65be-4094-bf63-673538e16da9"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""77a7f7d8-20b3-4a7d-85f8-865612e4b77d"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c3145c47-68e5-46a9-9b17-49b525dfef1a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""37bc852a-8bb2-4de7-96b3-b6932412b3ce"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d55b2051-1478-4f0d-9893-7624ec6196f9"",
                    ""path"": ""<Pointer>/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cast Skill 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a86b35f-b5db-4027-ba69-1313baf5c9fb"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cast Skill 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""69da9406-dfb5-46c6-8d0b-f0f160babae4"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cast Skill 3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4528607a-2f7b-4053-83ed-7f361f779e7d"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cast Skill 4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_Movement = m_Gameplay.FindAction("Movement", throwIfNotFound: true);
        m_Gameplay_CastSkill1 = m_Gameplay.FindAction("Cast Skill 1", throwIfNotFound: true);
        m_Gameplay_CastSkill2 = m_Gameplay.FindAction("Cast Skill 2", throwIfNotFound: true);
        m_Gameplay_CastSkill3 = m_Gameplay.FindAction("Cast Skill 3", throwIfNotFound: true);
        m_Gameplay_CastSkill4 = m_Gameplay.FindAction("Cast Skill 4", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
    private readonly InputAction m_Gameplay_Movement;
    private readonly InputAction m_Gameplay_CastSkill1;
    private readonly InputAction m_Gameplay_CastSkill2;
    private readonly InputAction m_Gameplay_CastSkill3;
    private readonly InputAction m_Gameplay_CastSkill4;
    public struct GameplayActions
    {
        private @GameControls m_Wrapper;
        public GameplayActions(@GameControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Gameplay_Movement;
        public InputAction @CastSkill1 => m_Wrapper.m_Gameplay_CastSkill1;
        public InputAction @CastSkill2 => m_Wrapper.m_Gameplay_CastSkill2;
        public InputAction @CastSkill3 => m_Wrapper.m_Gameplay_CastSkill3;
        public InputAction @CastSkill4 => m_Wrapper.m_Gameplay_CastSkill4;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void AddCallbacks(IGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @CastSkill1.started += instance.OnCastSkill1;
            @CastSkill1.performed += instance.OnCastSkill1;
            @CastSkill1.canceled += instance.OnCastSkill1;
            @CastSkill2.started += instance.OnCastSkill2;
            @CastSkill2.performed += instance.OnCastSkill2;
            @CastSkill2.canceled += instance.OnCastSkill2;
            @CastSkill3.started += instance.OnCastSkill3;
            @CastSkill3.performed += instance.OnCastSkill3;
            @CastSkill3.canceled += instance.OnCastSkill3;
            @CastSkill4.started += instance.OnCastSkill4;
            @CastSkill4.performed += instance.OnCastSkill4;
            @CastSkill4.canceled += instance.OnCastSkill4;
        }

        private void UnregisterCallbacks(IGameplayActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @CastSkill1.started -= instance.OnCastSkill1;
            @CastSkill1.performed -= instance.OnCastSkill1;
            @CastSkill1.canceled -= instance.OnCastSkill1;
            @CastSkill2.started -= instance.OnCastSkill2;
            @CastSkill2.performed -= instance.OnCastSkill2;
            @CastSkill2.canceled -= instance.OnCastSkill2;
            @CastSkill3.started -= instance.OnCastSkill3;
            @CastSkill3.performed -= instance.OnCastSkill3;
            @CastSkill3.canceled -= instance.OnCastSkill3;
            @CastSkill4.started -= instance.OnCastSkill4;
            @CastSkill4.performed -= instance.OnCastSkill4;
            @CastSkill4.canceled -= instance.OnCastSkill4;
        }

        public void RemoveCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameplayActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);
    public interface IGameplayActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnCastSkill1(InputAction.CallbackContext context);
        void OnCastSkill2(InputAction.CallbackContext context);
        void OnCastSkill3(InputAction.CallbackContext context);
        void OnCastSkill4(InputAction.CallbackContext context);
    }
}
